version: '3.8'

services:
  library-app:
    container_name: container_library
    image: applibrary:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    networks:
      - library
  postgres:
    image: postgres:latest 
    container_name: container_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    networks:
      - library

networks:
  library:
    driver: bridge

volumes:
  postgres_data:
